[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nash-ppo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chex>=0.1.91",
    "distrax>=0.1.7",
    "flax>=0.12.0",
    "jax[cuda]>=0.8.0; sys_platform == 'linux'",
    "jax>=0.8.0; sys_platform == 'darwin'",
    "grpcio>=1.76.0",
    "gymnasium[box2d,classic-control]>=1.2.1",
    "hydra-core>=1.3.2",
    "mlagents",
    "mlagents-envs",
    "numpy>=2.3.4",
    "omegaconf>=2.3.0",
    "orbax>=0.1.9",
    "setuptools<81",
    "tensorboard>=2.20.0",
    "torch>=2.9.0",
    "tqdm>=4.67.1",
]

[project.optional-dependencies]
pettingzoo = [
    "pettingzoo[mpe]>=1.15.0",
    "supersuit==3.4.0",
]

[tool.hatch.build.targets.wheel]
packages = ["agents", "envs", "train", "scripts"]

[tool.uv.sources]
mlagents-envs = { path = "../../../external/ml-agents/ml-agents-envs", editable = true }
mlagents = { path = "../../../external/ml-agents/ml-agents", editable = true }
