[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nash-ppo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chex>=0.1.91",
    "distrax>=0.1.7",
    "flax>=0.12.0",
    "gymnasium[box2d,classic-control]>=1.2.1",
    "hydra-core>=1.3.2",
    "jax[cuda]>=0.7.2; sys_platform == 'linux'",
    "jax>=0.7.2; sys_platform == 'darwin'",
    "mpe2>=0.0.1",
    "omegaconf>=2.3.0",
    "orbax>=0.1.9",
    "pettingzoo[mpe]>=1.25.0",
    "setuptools<81",
    "supersuit>=3.10.0",
    "tensorboard>=2.20.0",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
    "mlagents-envs",
    "mlagents",
]

[tool.hatch.build.targets.wheel]
packages = ["agents", "envs", "train", "scripts"]

[tool.uv.sources]
mlagents-envs = { git = "https://github.com/easonyu0203/ml-agents.git", subdirectory = "ml-agents-envs" }
mlagents = { git = "https://github.com/easonyu0203/ml-agents.git", subdirectory = "ml-agents" }
