lr: 3e-4
ent_coef: 0.01
clip_eps: 0.2
max_grad_norm: 1.0  # Maximum gradient norm for clipping
num_envs: 32
num_steps: 128
gamma: 0.998
gae_gamma: 0.95
num_minibatches: 4
num_ppo_epoch: 4
mag_coef: 0.01
num_inner_update: 100
num_outer_update: 10
bptt_length: 16 # BPTT truncation length (Only matter when use recurrent agent)
normalize_logprob: true  # Normalize log_prob and KL by action dimensions (important for multi-discrete)
normalize_value: true # Normalizing the value function's targets